spring:
  datasource:
    url: jdbc:mysql://47.96.159.71/oomall?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: oomall
    password: oomallp@$$w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: logService

eureka:
  client:
    service-url:
      defaultZone: http://47.96.159.71:8888/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.96.159.71
    non-secure-port: 8840

mybatis:
  type-aliases-package: com.tardybird.log.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8840